/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangRealisationsRouteImport } from './routes/$lang.realisations'
import { Route as LangExpertisesRouteImport } from './routes/$lang.expertises'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCollaborationRouteImport } from './routes/$lang.collaboration'
import { Route as LangAboutRouteImport } from './routes/$lang.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangRealisationsRoute = LangRealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => LangRoute,
} as any)
const LangExpertisesRoute = LangExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCollaborationRoute = LangCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/collaboration': typeof LangCollaborationRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/expertises': typeof LangExpertisesRoute
  '/$lang/realisations': typeof LangRealisationsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/collaboration': typeof LangCollaborationRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/expertises': typeof LangExpertisesRoute
  '/$lang/realisations': typeof LangRealisationsRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/collaboration': typeof LangCollaborationRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/expertises': typeof LangExpertisesRoute
  '/$lang/realisations': typeof LangRealisationsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/collaboration'
    | '/$lang/contact'
    | '/$lang/expertises'
    | '/$lang/realisations'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/collaboration'
    | '/$lang/contact'
    | '/$lang/expertises'
    | '/$lang/realisations'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/collaboration'
    | '/$lang/contact'
    | '/$lang/expertises'
    | '/$lang/realisations'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/realisations': {
      id: '/$lang/realisations'
      path: '/realisations'
      fullPath: '/$lang/realisations'
      preLoaderRoute: typeof LangRealisationsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/expertises': {
      id: '/$lang/expertises'
      path: '/expertises'
      fullPath: '/$lang/expertises'
      preLoaderRoute: typeof LangExpertisesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/collaboration': {
      id: '/$lang/collaboration'
      path: '/collaboration'
      fullPath: '/$lang/collaboration'
      preLoaderRoute: typeof LangCollaborationRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangCollaborationRoute: typeof LangCollaborationRoute
  LangContactRoute: typeof LangContactRoute
  LangExpertisesRoute: typeof LangExpertisesRoute
  LangRealisationsRoute: typeof LangRealisationsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangCollaborationRoute: LangCollaborationRoute,
  LangContactRoute: LangContactRoute,
  LangExpertisesRoute: LangExpertisesRoute,
  LangRealisationsRoute: LangRealisationsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
